# fly.toml app configuration file
app = "zeus"
primary_region = "cdg"

[build]

[env]
  PYTHONUNBUFFERED = "1"                   # imprime sans buffer
  GUNICORN_CMD_ARGS = "--access-logfile - --error-logfile - --log-level info"
  # Si tu es en uvicorn Ã  la place, commente la ligne ci-dessus et mets :
  # UVICORN_LOG_LEVEL = "info"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  path         = "/health"
  grace_period = "30s"
  interval     = "5s"
  timeout      = "2s"
  method       = "GET"
  protocol     = "http"

[[mounts]]
  source = "data"
  destination = "/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1